<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP6g1rlw\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP6g1rlw/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerP6g1rlw.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerP6g1rlw\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerP6g1rlw\App_KernelDevDebugContainer([
    'container.build_hash' => 'P6g1rlw',
    'container.build_id' => '1f1e517d',
    'container.build_time' => 1592067232,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP6g1rlw');
