<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'get_one_event' => [['id'], ['_controller' => 'App\\Controller\\EventController::getEvent'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/events']], [], []],
    'get_all_events' => [[], ['_controller' => 'App\\Controller\\EventController::getAllEvents'], [], [['text', '/events']], [], []],
    'add_event' => [[], ['_controller' => 'App\\Controller\\EventController::addEvent'], [], [['text', '/events']], [], []],
    'update_event' => [['id'], ['_controller' => 'App\\Controller\\EventController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/events']], [], []],
    'delete_event' => [['id'], ['_controller' => 'App\\Controller\\EventController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/events']], [], []],
    'get_one_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::getUser'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], []],
    'get_all_users' => [[], ['_controller' => 'App\\Controller\\UserController::getAllUsers'], [], [['text', '/users']], [], []],
    'add_user' => [[], ['_controller' => 'App\\Controller\\UserController::addUser'], [], [['text', '/users']], [], []],
    'update_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::update'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], []],
    'delete_user' => [['id'], ['_controller' => 'App\\Controller\\UserController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/users']], [], []],
];
